config/routes.rb
Rails.application.routes.draw do
  resources :purchases, only: [:index, :new, :create, :show] do
    member do 
      post 'charge'
    end 
  end

  resources :queries
  resources :reviews
  resources :addresses
  resources :profiles
  get 'pages/home'
  get 'pages/contact'
  post 'pages/contact', to: 'pages#contact_email'

  resources :photos
  resources :bicycles
  devise_for :users

  root 'pages#home'

end

app/models/profile.rb
class Profile < ApplicationRecord
  include ImageUploader::Attachment.new(:avatar) # adds an `avatar` virtual attribute
  belongs_to :user
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @addresses = @profile.user.addresses
    @reviews = @profile.user.reviews

    def user_rating(reviews)
      all_ratings= []
      reviews.each do |review|
        rating = review.rating
        all_ratings.push rating
      end
      max = all_ratings.count * 5
      sum = all_ratings.sum
      if max != 0 
      percentage =  sum * 100/max 
      result = percentage * 5/100.00
      else 
        result = nil 
      end
      return result

    end

    if @reviews.nil?
      @user_rating == nil 
    else
      @user_rating = user_rating(@reviews) 
    end



  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    authorize @profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
    authorize @profile
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
    authorize @profile

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find(params[:id])
  end
  def set_user 
    @user = @profile.user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :avatar, :username, :user_id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
    <% if profile.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

            <ul>
                <% profile.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <p>   <%= form.label :first_name %></p>
        <%= form.text_field :first_name, id: :profile_first_name, required: true %>
    </div>

    <div class="field">
<p>        <%= form.label :last_name %></p>
        <%= form.text_field :last_name, id: :profile_last_name, required: true %>
    </div>

    <div class="field">
        <% if profile.avatar_data.present? %>
            <div class="avatar">  <%= image_tag profile.avatar_url(:small) %></div>
    <% end %>
        <% form.hidden_field :image, value: profile.cached_avatar_data %>
   <p>     <%= form.label :avatar %></p>
        <%= form.file_field :avatar, id: :profile_avatar_data %>
    </div>

    <div class="field">
     <p>   <%= form.label :username %></p>
        <%= form.text_field :username, id: :profile_username, required: true %>
    </div>

    <div class="field">
        <%= form.hidden_field :user_id, value:  current_user.id, id: :profile_user_id, required: true  %>
    </div>

    <div class="actions">
        <%= form.submit "confirm", class: "submit-button" %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="devise-login">
<div class="login-form">
    <p><h1>Editing Profile</h1></p>

<%= render 'form', profile: @profile %>

</div>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Avatar data</th>
      <th>Username</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= image_tag profile.avatar_url(:small) %></td>
        <td><%= profile.username %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <% if policy(profile).update? %>

            <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<div class="devise-login">
<div class="login-form">
    <p><h1>New Profile</h1></p>

<%= render 'form', profile: @profile %>

</div>
</div>

app/views/profiles/show.html.erb
<div class="showprofile">
    <p id="notice"><%= notice %></p>
    <div class="avatar">
        <%= image_tag @profile.avatar_url(:small) %>
    </div>
    <div>
        <%= @profile.username %>
    </div>
    <div class="profile-card">
        <% @addresses.each do |a| %>
            <p> <%= a.address %></p>
            <div class="map">
                <%= image_tag ("https://maps.googleapis.com/maps/api/staticmap?center=#{a.latitude},#{a.longitude}&zoom=12&size=400x200&markers=color:blue%7Clabel:#{@profile.first_name.first}%7C#{a.latitude},#{a.longitude}&key=#{ENV.fetch('GOOGLE_KEY')}") %>

            </div>
            <% if policy(@profile).update? %>
                <div class="submit">
                    <p>
                    <%= link_to 'delete location', a, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </p>
                </div>
                <div class="submit">
                    <p>
                    <%= link_to 'edit location', edit_address_path(a) %>
                    </p>
                </div>
            <% end %>

        <% end %>

        </p>
        <p>

        <% if policy(@profile).update? %>
            <div class="submit">
                <p>
                <%= link_to "add location", new_address_path(user_id: @user.id) %>
                </p>
            </div>
            <div class="submit">
                <p>
                <%= link_to 'edit your profile', edit_profile_path(@profile) if policy(@profile).update? %> 
                </p>
            </div>
        <% end %>
        <div><strong>reviews</strong>
            <div>
                <p>
                rating:<%= @user_rating unless @user_rating.nil? %> stars
                </p>
            </div>

            <div class="review profile-card">
                <% already_reviewed = [] %>
                <% @reviews.each do |review| %>
                    <%   already_reviewed.push review.reviewer %> 
                    <div class="avatar"><%= image_tag review.reviewer.profile.avatar_url(:small) %></div> <p><strong> <%= review.reviewer.profile.username %> </strong> </p>
                    <p><%= review.content  %> </p>
                    <p><%= review.rating %> stars for <%= @profile.username %> </p>
                <% end %>

                <% unless current_user.in?(already_reviewed) || current_user == @profile.user ||current_user.nil? %>
                    <div class="button"> 
                        <%= link_to "Review #{@profile.username} ", new_review_path(reviewed_user: @profile.user, reviewer: current_user, user_id: @profile.user) %>
                    </div> 
                <% else %>
                    <div> <p>There are no reviews</p> </div>
    <% end  %>
            </div>
        </div>

    </div>
</div>