config/routes.rb
Rails.application.routes.draw do
  resources :purchases, only: [:index, :new, :create, :show] do
    member do 
      post 'charge'
    end 
  end

  resources :queries
  resources :reviews
  resources :addresses
  resources :profiles
  get 'pages/home'
  get 'pages/contact'
  post 'pages/contact', to: 'pages#contact_email'

  resources :photos
  resources :bicycles
  devise_for :users

  root 'pages#home'

end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
  belongs_to :user
  has_many :photos 
  has_many :queries

  def self.search(search)
    where("LOWER(title) LIKE ? OR LOWER(description) LIKE ? OR LOWER(brand) LIKE ? ", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%" )
  end
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_bicycle, only: [:show, :edit, :update, :destroy]
  before_action :check_profile?


  # GET /bicycles
  # GET /bicycles.json
  def index
    @bicycles  = policy_scope(Bicycle)
 
  
  end

  # GET /bicycles/1
  # GET /bicycles/1.json
  def show
    @photos = @bicycle.photos
    @queries = @bicycle.queries
    @owner = @bicycle.user.profile
    @purchase = Purchase.new
  end

  # GET /bicycles/new
  def new
    @bicycle = Bicycle.new
  end

  # GET /bicycles/1/edit
  def edit
    @bicycle = Bicycle.find(params[:id])
  end

  # POST /bicycles
  # POST /bicycles.json
  def create
    @bicycle = Bicycle.new(bicycle_params)
    @bicycle.user = current_user

    respond_to do |format|
      if @bicycle.save
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycles/1
  # PATCH/PUT /bicycles/1.json
  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
    authorize @bicycle
  end

  # DELETE /bicycles/1
  # DELETE /bicycles/1.json
  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to bicycles_url, notice: 'Bicycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bicycle
    @bicycle = Bicycle.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bicycle_params
    params.require(:bicycle).permit(:title, :price, :description, :brand, :size, :colour, :gender, :year)
  end


end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/views/bicycles/_form.html.erb
<%= form_with(model: bicycle, local: true) do |form| %>
    <% if bicycle.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(bicycle.errors.count, "error") %> prohibited this bicycle from being saved:</h2>

            <ul>
                <% bicycle.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <p>       <%= form.label :title %></p>
        <%= form.text_field :title, id: :bicycle_title, required: true %>
    </div>

    <div class="field">
      <p>  <%= form.label :price %></p>
        <%= form.text_field :price, id: :bicycle_price, required: true %>
    </div>

    <div class="field">
        <p><%= form.label :description %></p>
        <%= form.text_area :description, id: :bicycle_description, required: true %>
    </div>

    <div class="field">
       <p> <%= form.label :brand %></p>
        <%= form.text_field :brand, id: :bicycle_brand, required: true %>
    </div>


    <div class="field">
       <p> <%= form.label :size %></p>
        <%= form.select :size, ["", "XS(extrasmall)", "S(small)", "M(medium)", "L(large)", "XL(extra large)"], id: :bicycle_size, required: true %>
    </div>

    <div class="field">
       <p> <%= form.label :colour %></p>
        <%= form.text_field :colour, id: :bicycle_colour, required: true %>
    </div>

    <div class="field">
        <p> <%= form.label :gender %> </p>
        <%= form.select :gender,["unisex","female", "male"], id: :bicycle_gender, required: true %>
    </div>

    <div class="field">
       <p> <%= form.label :year %>
        <%= form.text_field :year, id: :bicycle_year, required: true %>
    </div>
    <% @bicycle.photos.each do |photo| %>
        <%# <%= render '/photos/form', photo: photo, bicycle: @bicycle  %1> %>
        <%=    image_tag photo.image_url(:medium) %>
        <p class="button">  <%= link_to 'Delete this photo', photo, method: :delete, data: { confirm: 'Are you sure?' }%></p>
    <% end %> 
    <% if @bicycle.id.nil? %>

    <% else %>
        <p class="button"><%= link_to 'Add photos', new_photo_path(bicycle_id: @bicycle.id) %></p>
    <% end %>




    <div class="actions">
        <%= form.submit "continue to bicycle", class: "submit-button" %>
    </div>
<% end %>

app/views/bicycles/edit.html.erb
<div class="devise-login">
<div class="login-form">

    <p><h1>Editing Bicycle</h1></p>

<%= render 'form', bicycle: @bicycle %>

<%# <p class="button"><%= link_to 'Show', @bicycle %1> </p? %>
<%# <p class="button"><%= link_to 'Back', bicycle_path(@bicycle) %1></p> %>

</div>
</div>

app/views/bicycles/index.html.erb
<p id="notice"><%= notice %></p>
<p><%= flash[:alert] %><p>


<div class="devise-login"><p> <h1>my bicycles </h1></p> </div>

<div class="card-wrapper">
    <% @bicycles.each do |bicycle| %>
        <div class="card">
            <div class="date"><p> <%= bicycle.created_at.in_time_zone("Melbourne").strftime("%d %b %y") %> </p> </div>
            <div class="title-content">
                <div class="bicycle_element title"> 

                    <div class="titletitle"><p><%= bicycle.title %></p> </div>
                    <div class="avatar">
                        <%=link_to( image_tag(bicycle.user.profile.avatar_url(:small)), profile_path(bicycle.user.id),) %>
                    </div>


                </div>
                <div class="content">

                    <div class="bicycle_element photo">   
                        <%= link_to ( image_tag bicycle.photos.first.image_url(:small)), bicycle_path(bicycle.id) %> 
                    </div>
                    <div class="details">
                        <div class="bicycle_element first"> <p>   <%= number_to_currency(bicycle.price, unit: "AUD $") %> </p> </div>
                        <div class="bicycle_element second">
                            <% if bicycle.user.addresses.empty? %>    
                            <% else %>
                                <p>   <%= bicycle.user.addresses.first.suburb  %> </p>
                            <% end %>
                        </div>
                        <div class="bicycle_element third"> <p>   <%= bicycle.size %></p> </div>
                        <div class="bicycle_element forth"> <p>   <%= bicycle.user.addresses.first.state %></p> </div>
                    </div>
                </div>
                <div class="devise-login edit-buttons">
                    <div class="bicycle_element"> <p>   <%= bicycle.description %></p> </div>

                </div>

                <div class="devise-login edit-buttons">
                    <div class="button"><%= link_to 'show', bicycle %></div>
                    <div class="button"><%= link_to 'edit', edit_bicycle_path(bicycle) %></div>
                    <div class="button"><%= link_to 'delete', bicycle, method: :delete, data: { confirm: 'Are you sure?' } %></div>

                    <% if bicycle.user.addresses.nil? %>
                        <div class="button">
                            <%= link_to "add location", new_address_path(user_id: current_user.id) %>
                        </div>
                    <% else %>
                    <% end %>



                </div>

            </div>
        </div>
    <% end %>

</div>

<div class="devise-login">
    <p class="button"> <%= link_to 'new bicycle', new_bicycle_path %> <p>
</div>

app/views/bicycles/new.html.erb
<div class="devise-login">
<div class="login-form">

    <p><h1>New Bicycle</h1></p>

<%= render 'form', bicycle: @bicycle %>
</div>
</div>

app/views/bicycles/show.html.erb
<div class="showbicycle">

    <div class="profile-card">
        <p id="notice"><%= notice %></p> 
        <% if @photos.first.nil?%>
        <% else %>
            <div class="photoviewer">  
                <%# <% @photos.each do |photo| %1> %>
                <%#     <%= image_tag photo.image_url(:medium) %1> %>
                <%# <% end %1> %>
            <%= image_tag @photos.first.image_url(:medium) %>
            </div>
        <% end %>
        <% if policy(@bicycle).update? %>
            <p class="button">    <%= link_to 'add photos', new_photo_path(bicycle_id: @bicycle)  %></p>
        <% else %>
        <% end%>
        <p>
        <strong><%= @bicycle.title %> </strong>
        </p>
        <div class="bicycle-details">
            <p>
            <strong> Posted: </strong>
            <%= @bicycle.created_at.strftime("%d %b %y") %>
            </p>
            <p>
            <strong> Updated: </strong>
            <%= @bicycle.updated_at.strftime("%d %b %y") %>
            </p>

            <p>
            <strong>Price:</strong>
            <%= @bicycle.price %>
            </p>


            <p>
            <strong>Brand:</strong>
            <%= @bicycle.brand %>
            </p>

            <p>
            <strong>Size:</strong>
            <%= @bicycle.size %>
            </p>

            <p>
            <strong>Colour:</strong>
            <%= @bicycle.colour %>
            </p>

            <p>
            <strong>Gender:</strong>
            <%= @bicycle.gender %>
            </p>

            <p>
            <strong>Year:</strong>
            <%= @bicycle.year %>
            </p>


            <p>
            <strong>Owner:</strong>
            <%= link_to "#{@owner.username} ", profile_path(@bicycle.user.id) %>
            </p>
            <p>
            <strong>Description:</strong>
            <%= @bicycle.description %>
            </p>
        </div>

        <% if policy(@bicycle).update? %>
            <p class="button">    <%= link_to 'Edit', edit_bicycle_path(@bicycle) %> </p>
        <% end %>
        <% if user_signed_in? && current_user != @bicycle.user  %>
            <%= form_for @purchase, :url => purchases_path(@purchase), :html => {:method => :post} do |f| %>
                <%= f.hidden_field :pickup, value: false %>
                <%= f.hidden_field :delivery_address, value: current_user.addresses.first.id %>
                <%= f.hidden_field :bicycle_id, value: @bicycle.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <p >   <%= f.submit "Buy", class: "button"%></p>
            <% end %>
        <% end %>




    </div>
    <div class="profile-card">
        <div><p> questions board </p></div>
        <% if user_signed_in? && current_user != @bicycle.user  %>
            <p class="button"> 
            <%= link_to 'Ask a question', new_query_path(bicycle_id: @bicycle)  %></p>

            <p>
        <% else %>

        <% end %>
        <% @queries.each do |query| %>
            <div class="reviewcard">
                <p> <%= query.created_at.strftime("%d %b %y")%> </p>
                <div class="userfield">
                    <strong> <p> <%= query.user.profile.username %>:</p></strong>
                    <p class="avatar"> <%= image_tag query.user.profile.avatar_url(:small) %></p> 

                </div>
                <p><%= query.question %></p>
                <strong> <p> <%= @owner.username %> (owner): </p> </strong>
                <% if query.answer.present? %>
                    <p class="response"><%= query.answer %> </p>
                <% else %>
                    <p class="response italic">Question is awaiting response from <%= @owner.username %> </p>

                <% end %>
                <% if  @bicycle.user == current_user && query.answer.nil?  %>
                    <div class="answerbutton"> <p><%= link_to "Answer this question", edit_query_path(query) %> </p> </div> 
                <% else %>


                <% end %>

            </div>

        <% end %>
    </div>
</div>