config/routes.rb
Rails.application.routes.draw do
  resources :purchases, only: [:index, :new, :create, :show] do
    member do 
      post 'charge'
    end 
  end

  resources :queries
  resources :reviews
  resources :addresses
  resources :profiles
  get 'pages/home'
  get 'pages/contact'
  post 'pages/contact', to: 'pages#contact_email'

  resources :photos
  resources :bicycles
  devise_for :users

  root 'pages#home'

end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader::Attachment.new(:image) # adds an `image` virtual attribute
  belongs_to :bicycle

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
    authorize @photos

  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    authorize @photo
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @bicycle = Bicycle.find(params[:bicycle_id])
    
  end

  # GET /photos/1/edit
  def edit
      @photo = Photo.find(params[:id])
      @bicycle = Bicycle.find(photo.bicycle_id)
      authorize @photo
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    authorize @photo


    respond_to do |format|
      if @photo.save
        format.html { redirect_to edit_bicycle_path(@photo.bicycle_id), notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
    authorize @photo
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to edit_bicycle_path(@photo.bicycle_id), notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
    authorize @photo
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_bicycle 
      @photo = Photo.find(params[:id])
      @bicycle = Bicycle.find(photo.bicycle_id)

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :bicycle_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">

      <%= form.hidden_field :image, value: photo.cached_image_data %>
        <%= form.file_field :image, required: true %>
    </div>

    <div class="field">
        <%# <%= form.label :bicycle_id %1> %>
        <%= form.hidden_field :bicycle_id, value:  bicycle.id, required: true %>
    </div>


  <div class="actions">
    <%= form.submit "add photo", class: "submit-button" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="devise-login">
<div class="login-form">

    <p><h1>Editing Photo</h1></p>

<%= render 'form', photo: @photo %>

<p class="button"><%= link_to 'Show', @photo %> </p>
<p class="button"><%= link_to 'Back', bicycles_path(params[:bicycle_id]) %></p>


</div>
</div>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Image data</th>
      <th>Bicycle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.image_data %></td>
        <td><%= photo.bicycle %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<div class="devise-login">
<div class="login-form">

    <p><h1>add a new photo </h1><p>

<%= render 'form', photo: @photo, bicycle: @bicycle %>

<%= link_to 'Back', bicycles_path(params[:bicycle_id]) %>
</div>
</div>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image data:</strong>
  <%= image_tag @photo.image_url(:medium) %>
</p>

<p>
  <strong>Bicycle:</strong>
  <%= @photo.bicycle %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>