config/routes.rb
Rails.application.routes.draw do
  resources :purchases, only: [:index, :new, :create, :show] do
    member do 
      post 'charge'
    end 
  end

  resources :queries
  resources :reviews
  resources :addresses
  resources :profiles
  get 'pages/home'
  get 'pages/contact'
  post 'pages/contact', to: 'pages#contact_email'

  resources :photos
  resources :bicycles
  devise_for :users

  root 'pages#home'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
  def address
  [house_number, street_number, street, suburb, city, state, postal_code, country_code].compact.join(' ')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
  belongs_to :user
  has_many :photos 
  has_many :queries

  def self.search(search)
    where("LOWER(title) LIKE ? OR LOWER(description) LIKE ? OR LOWER(brand) LIKE ? ", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%" )
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader::Attachment.new(:image) # adds an `image` virtual attribute
  belongs_to :bicycle

end

app/models/profile.rb
class Profile < ApplicationRecord
  include ImageUploader::Attachment.new(:avatar) # adds an `avatar` virtual attribute
  belongs_to :user
  
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :bicycle
end

app/models/query.rb
class Query < ApplicationRecord
  belongs_to :bicycle
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewer, class_name: "User", foreign_key: "reviewer_id"
  belongs_to :reviewed_user, class_name: "User", foreign_key: "reviewed_user_id"
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_one :profile 
  has_many :addresses 
  has_many :done_reviews,    class_name: "Review", foreign_key: "reviewer_id"
  has_many :received_reviews, class_name: "Review", foreign_key: "reviewed_user_id"
  has_many :reviews, class_name: "Review", foreign_key: "user_id"
  has_many :purchases
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_profile?
  before_action :check_available_bicycles?

  def home
    @purchases = Purchase.all
    bikes = Bicycle.all
    @bicycles = []
    bikes.each do |b|
      unless Purchase.find_by bicycle_id: b 
        @bicycles.push b 
      end
    end
    ### search bar ###
    if params[:search]
      @bicycles = Bicycle.search(params[:search]).order("created_at DESC") 
    else
      @bicycles = @bicycles
    end
    def contact_email
      user = current_user
      ContactMailer.send_contact_email(user: user, params: email_params).deliver_now

      redirect_to root_path
    end


  end
      private
    def email_params
      params.require(:contact).permit(:name, :message)

    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
    authorize @photos

  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    authorize @photo
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @bicycle = Bicycle.find(params[:bicycle_id])
    
  end

  # GET /photos/1/edit
  def edit
      @photo = Photo.find(params[:id])
      @bicycle = Bicycle.find(photo.bicycle_id)
      authorize @photo
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    authorize @photo


    respond_to do |format|
      if @photo.save
        format.html { redirect_to edit_bicycle_path(@photo.bicycle_id), notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
    authorize @photo
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to edit_bicycle_path(@photo.bicycle_id), notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
    authorize @photo
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_bicycle 
      @photo = Photo.find(params[:id])
      @bicycle = Bicycle.find(photo.bicycle_id)

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :bicycle_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title> bikeSquare </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <header>     
                <div class="logo"><%= link_to (image_tag("Logov3.png", alt: "bikeSquare logo" )), root_path %></div>
            <% if user_signed_in? %>
                <nav>
                    
                    <div class="avatar-top">
                        <% if current_user.profile.present? %>
                            <%= link_to ( image_tag current_user.profile.avatar_url(:small)), profile_path(current_user.profile) %> 
                        <% else %>
                        <% end %>
                    </div>
                    <div> <p> <%= link_to "my bicycles", bicycles_path %></p> </div>
                    <% unless current_user.profile.nil? %>
                        <div><p> <%= link_to "my profile", profile_path(current_user.profile.id)  %></p> </div>
                    <% end %>
                    <div><p> <%= link_to "my purchases", purchases_path  %> </p></div>
                    <div><p> <%= link_to "sign out", destroy_user_session_path, method: :delete %></p> </div>
                </nav>

            <% else %>
                <div class="nav">
                    <div><p>  <%= link_to 'new bicycle', new_bicycle_path %> </p></div>
                    <div><p> <%= link_to "sign in", new_user_session_path %></p></div>
                </div>
            <% end %>
            <div class="search_form"> 
                <%= form_tag(pages_home_path, :method => "get", id: "search-form") do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Search bicycles" %>
                    <%= submit_tag "Search", class: "search_button" %>
                <% end %>
            </div>
            <% if user_signed_in? && current_user.profile.present? %>
                <div class="useremail">
                    <div><p> <%= current_user.profile.first_name %> <%= current_user.profile.last_name %></p> </div>
                </div>
            <% else %>

            <% end %>
        </header>


        <main>

            <%= yield %>
        </main>
        <footer>
            <%= link_to "Contact Us", pages_contact_path %>
            <%= link_to "About bikeSquare", pages_contact_path %>
            <%= link_to "Legal", pages_contact_path %>
        </footer>
    </body>

</html>

app/views/pages/contact.html.erb
<div class="devise-login">
<div class="login-form">


<%= form_for :contact do |f| %>
    <p>
    <%= f.text_field  :name, placeholder: "name" %>
    </p>

    <p>
    <%= f.text_area  :message, placeholder: "message" %>
    </p>

    <p >
    <%= f.submit 'send', class: "submit-button"%>
    </p>



<% end %>
</div>
</div>

app/views/pages/home.html.erb
<div class="showbicycle">
    <p id="notice"><%= notice %></p>
    <p><%= flash[:alert] %><p>
</div>

<div class="article">
    <div> 
        <h3> bikeSquare is here! </h3>
        <p> <strong>bikeSquare </strong> is where your purchase quality bikes from members of the communities all over Australia!</p> </div>
    <div> 
        <h3> Safe and easy! </h3>
        <p>It is easy, save and payment are secure! No more stresful cash transactions on the street.
        Always check the user reviews as well as remember to review people you bought from. It helps everyone making sure the bikes come from trustworthy source</p> 
    </div>
</div>

<div class="card-wrapper">
    <% @bicycles.each do |bicycle| %>
        <div class="card">
            <div class="date"> <p><%= bicycle.created_at.in_time_zone("Melbourne").strftime("%d %b %y") %></p> </div>
            <div class="title-content">
                <div class="bicycle_element title"> 

                    <div class="titletitle"><p><%= bicycle.title %></p> </div>
                    <div class="avatar">
                        <%=link_to( image_tag(bicycle.user.profile.avatar_url(:small)), profile_path(bicycle.user.profile),) %>
                    </div>


                </div>
                <div class="content">

                    <div class="bicycle_element photo">   
                        <%= link_to ( image_tag bicycle.photos.first.image_url(:small)), bicycle_path(bicycle.id) %> 
                    </div>
                    <div class="details">
                        <div class="bicycle_element first"> <p>   <%= number_to_currency(bicycle.price, unit: "AUD $") %> </p> </div>
                        <div class="bicycle_element second"> <p>  
                            <%= bicycle.user.addresses.first.suburb %> </p>
                        </div>
                        <div class="bicycle_element third"> <p>   <%= bicycle.size %></p> </div>
                        <div class="bicycle_element forth"> <p>   <%= bicycle.user.addresses.first.state %></p> </div>
                    </div>
                </div>
                <div class="devise-login">
                    <div class="bicycle_element"> <p>   <%= bicycle.description %></p> </div>

                </div>

            </div>
        </div>
    <% end %>

</div>